Remove KJ_LIFETIMEBOUND from StringPtr constructor.
KJ_LIFETIMEBOUND causes false alarms when compiling with clang 21.

For example in workerd:

```
bazel-out/k8-dbg/bin/external/workerd/src/workerd/io/_virtual_includes/io/workerd/api/streams/../basics.h:36:14: error: initializing pointer member 'type' with the stack address of parameter 'ownType' [-Werror,-Wdangling-field]
   36 |       : type(ownType),
      |              ^~~~~~~
bazel-out/k8-dbg/bin/external/workerd/src/workerd/io/_virtual_includes/io/workerd/api/streams/../basics.h:198:17: note: pointer member declared here
  198 |   kj::StringPtr type;
      |                 ^
```